version: '3'
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
      args:
        profile: ${PROFILE}
    ports:
      - 80:80
    depends_on:
      - local-storage-service
      - job-service
